name: Dev workflow

on:
  schedule:
    - cron:  '35 7 * * 0' # At 07:35 on Sunday
  pull_request:
    branches: [main, pre-release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
    with:
      operating-systems: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
      python-versions: "['3.9', '3.10', '3.11']"
      delete-poetry-lock: true # ${{ github.event_name == 'schedule' }} # the scheduled build tests against newer dependencies
    secrets: inherit
